jupyter/try-jupyter

- README.md
old link (https://jtpio.github.io/try-jupyter) wasn't working so switched to new one (https://jupyter.org/try-jupyter)
> DOC: update lite-badge link

- requirements.txt
This brings a couple of enhancements coming from JupyterLab 3.3.
> Update to `jupyterlite==0.1.0b2`

- requirements.txt
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b5
> Update to `jupyterlite==0.1.0b5`

- requirements.txt
Bringing the latest enhancements and bug fixes from the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b6
> Update to `jupyterlite==0.1.0b6`

- requirements.txt
Which updates to the latest JupyterLab 3.4 packages.
See https://discourse.jupyter.org/t/jupyterlab-3-4-0-is-released/14106 for more info.
> Update to `jupyterlite==0.1.0b7`

- requirements.txt
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b8
> Update to `jupyterlite==0.1.0b8`

- requirements.txt
New release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b10
Which adds support for offline mode and using JupyterLite as an app: https://github.com/jupyterlite/jupyterlite/pull/686
> Update to `jupyterlite==0.1.0b10`

- requirements.txt
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b12
> Update to `jupyterlite==0.1.0b12`

- requirements.txt
Update to the latest release to enable support for ipywidgets 8: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b13
> Update to `jupyterlite==0.1.0b13`

- .github/workflows/deploy.yml
Fixes https://github.com/jupyter/try-jupyter/issues/22
> Deploy to Pages with GitHub Actions

- requirements.txt
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b15
> Update to JupyterLite 0.1.0b15

- requirements.txt
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b16
> Update to `jupyterlite==0.1.0b16`

- requirements.txt
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b17
> Update to `jupyterlite==0.1.0b17`

- .github/workflows/rtd-preview.yml
Follow-up to https://github.com/jupyter/try-jupyter/pull/28.
> Create `rtd-preview.yml` workflow

- .github/workflows/rtd-preview.yml
Point to the correct link in the ReadTheDocs preview comment.
> Fix link in the ReadTheDocs preview

- environment.yml
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b22
Which fixes an issue when uploading large files.
> Update to `jupyterlite-core==0.1.0b22`

- environment.yml
This should fix ipywidgets: https://github.com/jupyterlite/pyodide-kernel/releases/tag/v0.0.6
Also update to Python 3.11 underneath.
> Update to `jupyterlite-pyodide-kernel==0.0.6`

- environment.yml
Update to https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0rc0
> Update to `jupyterlite-core==0.1.0rc0`

- environment.yml
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0
> Update to `jupyterlite-core==0.1.0`

- environment.yml
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.2
> Update to `jupyterlite-core=0.1.2`

- environment.yml
Update to the latest releases:
- https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.3
- https://github.com/jupyterlite/pyodide-kernel/releases/tag/v0.1.3
> Update `jupyterlite-core` and `jupyterlite-pyodide-kernel`

- environment.yml
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.2.2
> Update to `jupyterlite-core==0.2.2`

- environment.yml
Update to https://github.com/jupyterlite/jupyterlite/releases/tag/v0.3.0
> Update to JupyterLite 0.3.0

- environment.yml
Update to:
- https://github.com/jupyterlite/pyodide-kernel/releases/tag/v0.3.2
- https://github.com/jupyterlite/jupyterlite-sphinx/releases/tag/v0.15.0
> Update `jupyterlite-pyodide-kernel` and `jupyterlite-sphinx`

- environment.yml
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.4.0
> Update to JupyterLite 0.4.0

- .github/workflows/deploy.yml
> Update to `mamba-org/setup-micromamba@v1`

- environment.yml
Update to the latest versions.
> Update JupyterLite dependencies

- environment.yml
And bump a couple of other packages.
> Update to JupyterLite 0.6.0

- README.md
`contents/Intro.ipynb` -> `notebooks/Intro.ipynb`
> Fix notebook name in README
